#!/bin/sh
# Workspaces

ws1="web"
ws2="dev"
ws3="sla"
ws4="com"
ws5="med"
ws6="ran"

bspc config focused_border_color "#AB4642"
bspc config active_border_color "#AB4642"
bspc config presel_border_color "#B8B8B8"
bspc config urgent_border_color "#DC9565"
bspc config normal_border_color "#181818"

bspc config border_width 1
bspc config window_gap 0
bspc config normal_border_color "#585858"

bspc config top_padding 18
bspc config split_ratio 0.5
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config click_to_focus button1
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

if [ $(uname -n) = 'lf-x250' ]; then
	external_monitor=$(xrandr --query | grep '^DP-1')
	if [[ $external_monitor = *disconnected* ]]; then
		xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off
		bspc monitor eDP-1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
	else
		xrandr --output DP-1 --mode 3440x1440 --pos 0x0 --rotate normal --output eDP-1 --off
		bspc monitor DP-1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
	fi
fi

if [ $(uname -n) = 'lf-t480s' ]; then
	external_monitor=$(xrandr --query | grep '^DP-2-1')
	if [[ -z "$external_monitor" ]] || [[ $external_monitor = *disconnected* ]]; then
		xrandr --output eDP-1 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-2-1 --off
		bspc monitor eDP-1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
	else
		xrandr --output DP-2-1 --mode 3440x1440 --pos 0x0 --rotate normal --set audio on --output eDP-1 --off
		bspc monitor DP-2-1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
	fi
fi

if [ $(uname -n) = 'lf-pc' ]; then
	xrandr HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-1 --mode 1920x1080 --pos 1920x0 --rotate normal
	bspc monitor HDMI-A-0 -d $ws1 $ws2 $ws3
	bspc monitor HDMI-A-1 -d $ws4 $ws5 $ws6
fi

if [ $(uname -n) = 'lf-x200' ]; then
	xrandr --output LVDS1 --primary --mode 1280x800 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output DP3 --off --output HDMI1 --off --output HDMI2 --off --output VGA1 --off --output VIRTUAL1 --off
	bspc monitor LVDS1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
fi

# LAUNCH PROGRAMS
~/.config/polybar/launch.sh &

pgrep -x sxhkd >/dev/null || sxhkd &

# pacman -Qqe > ~/.config/pkglist.txt

xsetroot -cursor_name left_ptr -solid black
setxkbmap -layout us,cz -variant ,qwerty &
xbindkeys &
xautolock -time 5 -locker "sflock -f fixed" -detectsleep &

bspc rule -a "Slack" desktop='^3'
bspc rule -a "discord" desktop='^3'
bspc rule -a "thunderbird" desktop='^4'
bspc rule -a "TelegramDesktop" desktop='^4'
bspc rule -a "spotify" desktop='^5'

pgrep -x blueman-applet >/dev/null || blueman-applet &
pgrep -x pasystray >/dev/null || pasystray &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x clipit >/dev/null || clipit &
pgrep -x flameshot >/dev/null || flameshot &
pgrep -x telegram >/dev/null || telegram-desktop &
pgrep -x slack >/dev/null || slack &
pgrep -x thunderbird >/dev/null || thunderbird &
pgrep -x solaar >/dev/null || solaar -w hide &
pgrep -x unclutter >/dev/null || unclutter -idle 10 &
